{% set version = "0.1.1rc25" %}

package:
  name: enspara
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/e/enspara/enspara-0.1.1rc25.tar.gz

#build:
  #noarch: python
  #number: 0
  #script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - numpy==1.16.5
    - cython
  run:
    - python

test:
  imports:
    - enspara

about:
  home: https://github.com/bowman-lab/enspara
  license: GPLv3
  summary: 'MSMs at Scale'
  description: |
    Enspara is primarily a python library, but it also contains a few applications for very common Markov-state model related tasks.

    MSM estimation and manipulation
    Turn-key applications for clustering and analysis
    Transition path theory
    Information theory
    Ragged ndarrays
  dev_url: https://github.com/bowman-lab/enspara
  doc_url: https://pypi.org/project/enspara/
  doc_source_url: https://enspara.readthedocs.io/en/latest/index.html
