name: Continuous Integration
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
  
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        set -eux
        sudo apt-get update
        sudo apt install libmpich12 libmpich-dev build-essential ca-certificates
    
    - name: Install Dependencies (Darwin)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        set -eux
        brew install mpich

    - name: Build and install package
      run: |
        source .venv/bin/activate
        python -m venv .venv
        python -m pip install -e .[dev,docs,mpi]

    - name: pytest (no MPI)
      if: always()
      run: |
        source .venv/bin/activate
        set -eux
        python -m pytest
    
    - name: pytest (MPI)
      if: always()
      run: |
        source .venv/bin/activate
        set -eux
        mpirun -n 2 python -m pytest -m 'mpi' # TODO: Test behavior depends on -n 2, this is bad and should be fixed
