name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  publish:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        python:
        - "3.11"
        - "3.12"
        - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v2.0.5
      with:
        environment-name: cb-env
        create-args: >-
          python=${{ matrix.python }}
          pip
          python-build
          twine
          conda-build
          anaconda-client
        condarc: |
          channels:
            - conda-forge
        cache-environment: true
        cache-downloads: true

    - name: Add bash hook
      shell: bash
      run: eval "$(micromamba shell hook --shell=bash)"

    - name: Install package
      shell: bash
      run: |
        set -eux
        micromamba activate cb-env
        pip install .[dev]

    - name: Build (PyPI)
      shell: bash
      if: ${{ always() }}
      id: pypi-build
      run: |
        set -eux
        micromamba activate cb-env
        python -m build .

    - name: Publish (PyPI)
      shell: bash
      id: pypi-publish
      if: ${{ steps.pypi-build.outcome == 'success' }}
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        set -eux
        micromamba activate cb-env
        twine upload dist/* --verbose --skip-existing

    - name: Generate Conda metadata
      shell: bash
      if: ${{ always() && matrix.os == 'ubuntu-latest' }}
      id: conda-meta
      run: |
        set -eux
        micromamba activate cb-env
        ./gen_meta.py

    - name: Build (Conda)
      shell: bash
      if: ${{ steps.conda-meta.outcome == 'success' && matrix.os == 'ubuntu-latest' }}
      id: conda-build
      run: |
        micromamba activate cb-env
        path=$(conda-build . --output)
        conda-build .
        echo "path=$path" >> $GITHUB_OUTPUT

    - name: Publish (Conda)
      shell: bash
      if: ${{ steps.conda-build.outcome == 'success' && matrix.os == 'ubuntu-latest' }}
      id: conda-publish
      run: |
        micromamba activate cb-env
        anaconda login --username $CONDA_USERNAME --password $CONDA_PASSWORD
        anaconda upload --user $CONDA_USERNAME "${{ steps.conda-build.outputs.path }}" --skip-existing
