name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy-pypi:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        python: 
        - "3.6"
        - "3.7"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy cython mdtraj
        pip install setuptools wheel twine
    - name: Build manylinux Python wheels
      uses: Longbowman/python-wheels-manylinux-build@v0.1.5
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: 'setuptools numpy cython mdtraj'
    - name: Setup
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        python setup.py sdist bdist_wheel
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/* --verbose
  deploy-miniconda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install essential libraries 
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpich12 libmpich-dev build-essential ca-certificates 
    - name: Setup conda
      uses: s-weigand/setup-conda@master
      with:
        python-version: 3.7
    - name: publish-to-conda
      uses: Longbowman/conda-package-publish-action@0.3.44
      with:
        subDir: '.'
        AnacondaUsername: ${{ secrets.CONDA_USERNAME }}
        AnacondaPassword: ${{ secrets.CONDA_PASSWORD }}
